# Generated once, never typed by a human, never appears in code or chat.
resource "random_password" "rds_password" {
  length  = 24
  special = true
  # RDS master password disallows '/', '@', '"', and space. We also exclude
  # backslash to avoid any shell/JSON-escaping surprises later when this
  # value gets injected into ECS task definitions.
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_secretsmanager_secret" "rds_password" {
  name        = "${var.project_name}/rds/password"
  description = "Master password for the RDS Postgres instance, generated by Terraform"
}

resource "aws_secretsmanager_secret_version" "rds_password" {
  secret_id     = aws_secretsmanager_secret.rds_password.id
  secret_string = random_password.rds_password.result
}

# The backend expects ONE connection string (DATABASE_URL), but the
# password above is just the raw password. We assemble the full string
# here — where the RDS endpoint is already known — and store THAT as a
# second secret, so the app code never has to change to read separate
# host/user/password pieces.
resource "aws_secretsmanager_secret" "database_url" {
  name        = "${var.project_name}/backend/database-url"
  description = "Full Postgres connection string for the backend, assembled from RDS + the generated password"
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id = aws_secretsmanager_secret.database_url.id
  # urlencode() is essential here: override_special above includes characters
  # like # % & = + : ? that are syntactically meaningful in a URL. Without
  # encoding, a generated password containing one of these would corrupt
  # the connection string and the backend would fail to parse/connect —
  # exactly the crash loop we hit before finding this.
  secret_string = "postgres://${aws_db_instance.main.username}:${urlencode(random_password.rds_password.result)}@${aws_db_instance.main.address}:5432/${aws_db_instance.main.db_name}"
}
